SunsetLabs-Game/Stark-Brawl

- contract/src/models/item.cairo
- contract/src/tests/test_item.cairo
> feat: model item

- contract/Scarb.lock
- contract/Scarb.toml
- contract/src/lib.cairo
- contract/src/models/character.cairo
- contract/src/tests/test_character.cairo
> Feat #2 model character

- contract/src/models/team.cairo
- contract/src/tests/test_team.cairo
**📌 Summary**
This PR introduces the Team model in contract/src/models/team.cairo, providing a structured way to manage teams of characters in the contract.
**📄 Implementation Details**
The Team model includes the following attributes and functions:
**🛠️ Attributes:**
- id: felt → Unique identifier for the team.
- members: felt* → Pointer to an array storing character IDs in the team.
**⚙️ Functions:**
- initialize_team(id: felt) -> Team → Initializes a new team with an empty members list.
- add_member(character_id: felt) → Adds a character to the team, ensuring no duplicates.
- remove_member(character_id: felt) → Removes a character from the team.
- is_team_alive() -> felt → Returns 1 if at least one member is alive, otherwise 0.
> Implement Team Model in Cairo

- contract/src/models/model.cairo
- contract/src/tests/test_model.cairo
> implemented match model

- client/.gitignore
- client/src/components/shop/BrawlersGrid.tsx
- client/src/components/shop/brawler-card.tsx
- client/src/components/shop/brawler-details-modal.tsx
- client/src/components/shop/brawler-image.tsx
- client/src/components/shop/shop-tabs.tsx
- client/src/pages/shop.tsx
🚀 Feature: Implement Brawlers Shop
Closes #27 
📌 Description
This PR implements the Brawlers Shop feature, including the Brawler model, shop grid, and modal interactions. The shop allows users to browse and interact with brawlers, displaying their details and enabling purchasing options.
✅ Changes Implemented
🔹 Created Brawler model with:
id: Unique identifier for each brawler.
name: The name of the brawler.
description: A short description of the brawler's abilities.
image: URL of the brawler's image.
price: Cost of the brawler in the shop's currency.
rarity: Rarity classification (e.g., common, rare, legendary).
isNew: Boolean flag indicating whether the brawler is new.
isNFT: Boolean flag indicating if the brawler is an NFT.
tokenId: Unique identifier for the brawler’s token (if …
> feat: Implement Brawlers-Shop

- client/src/components/game-modes/game-mode-card.tsx
- client/src/components/game-modes/game-modes-layout.tsx
- client/src/lib/game-data.ts
- client/src/lib/types.ts
This pull request introduces the **Game Modes Cards UI**, enhancing the **Game Modes Page** by displaying various playable modes in a structured and engaging manner, as outlined in issue #33.  
The **Game Modes Page** is designed to showcase different playable modes available in the game, each represented by a unique card containing essential information to assist players in selecting their preferred mode.  
- **Components Developed:**  
- **`GameModesLayout`**:  
- Manages the overall structure of the **Game Modes Page**.  
- Includes navigation tabs for **Characters, Game Modes, Leaderboard,** and **Events**.  
- Contains the container for **Game Mode Cards**.  
- **`GameModeCard`**:  
- Displays information for each game mode, including:  
- **Mode Name** (e.g., Battle Royale, Arena …
> feat: implement game modes cards

- client/src/components/SocialHub/SocialHubLayout.tsx
- client/src/components/SocialHub/sections/Friends.tsx
- client/src/components/SocialHub/sections/Friends/FriendCard.tsx
- client/src/components/SocialHub/sections/Friends/FriendsList.tsx
- client/src/types/friend.ts
Closes https://github.com/SunsetLabs-Game/Stark-Brawl/issues/21
> feat: add Friend list view

- client/src/App.tsx
- client/src/components/events/EventCard.tsx
- client/src/components/events/EventCounter.tsx
- client/src/components/events/EventHeader.tsx
- client/src/components/events/EventProgress.tsx
- client/src/components/events/EventRewards.tsx
- client/src/components/events/EventSearch.tsx
- client/src/components/events/EventTabs.tsx
- client/src/components/events/EventTypeTag.tsx
- client/src/components/events/FeaturedEvent.tsx
- client/src/components/events/LiveIndicator.tsx
- client/src/components/events/ParticipantCounter.tsx
- client/src/components/events/SideMenu.tsx
- client/src/components/events/events-page.tsx
- client/src/components/ui/input.tsx
- client/src/index.css
- client/src/pages/events.tsx
- client/src/types/events.ts
This PR introduces the complete **Events Page** into the Stark Brawl client.  
It includes all required components, types, layout, and styling for a dynamic, search-enabled and visually polished events experience.
- ➕ `EventsPage`: Main page for listing featured, live, upcoming, and past events.
- 🧩 Components:
- `FeaturedEvent.tsx`: Highlights the main event.
- `EventTabs.tsx`: Tabs for filtering between event states.
- `EventCard.tsx`: Individual event display with all details.
- `EventRewards.tsx`, `EventTypeTag.tsx`, `LiveIndicator.tsx`, `ParticipantCounter.tsx`, `EventCounter.tsx`, `EventProgress.tsx`
- `SideMenu.tsx` and `EventHeader.tsx`: Layout elements for structure.
- 🔍 `EventSearch.tsx`: Search bar to filter events by title, type or description.
- 🌄 Images applied using assets …
> feat: create events page

- client/src/components/SocialHub/sections/Messages.tsx
- client/src/components/SocialHub/sections/Messages/ChatPanel.tsx
- client/src/components/SocialHub/sections/Messages/FriendList.tsx
- client/src/components/SocialHub/sections/Messages/FriendListItem.tsx
- client/src/components/SocialHub/sections/Messages/MessageItem.tsx
- client/src/components/SocialHub/sections/Messages/types.ts
Close: #23 
https://github.com/user-attachments/assets/f5a636c2-57c7-4344-b900-66308788e2c5
> feat: messages-system

- client/src/App.tsx
- client/src/components/battle-pass/BattlePassHeader.tsx
- client/src/components/battle-pass/BattlePassPage.tsx
- client/src/components/battle-pass/Icons.tsx
- client/src/components/battle-pass/NavigationButton.tsx
- client/src/components/battle-pass/PremiumPassUpgrade.tsx
- client/src/components/battle-pass/ProgressBar.tsx
- client/src/components/battle-pass/RewardIcons.tsx
- client/src/components/battle-pass/RewardItem.tsx
- client/src/components/battle-pass/TierItem.tsx
- client/src/components/battle-pass/TierList.tsx
- client/src/pages/battle-pass.tsx
- client/src/types/types.ts
This PR implements a complete Battle Pass page UI based on the provided design specifications. The implementation includes all required components for displaying the current season, progress tracking, tier rewards system, and premium pass upgrade option. The UI is fully responsive and built with React and Tailwind CSS.
- **Season Information Display**: Shows current season title (Season 15: Cyber Revolution) and remaining days (24)
- **Progress Tracking**: Visual progress bar showing tokens collected (65/100) and percentage to next tier (65%)
- **Tier System**: Horizontal scrollable list of tiers with the following states:
- Completed tiers (with checkmark)
- Current active tier (highlighted)
- Locked future tiers
- **Reward System**: Each tier displays:
- Free rewards (blue border) with …
> Implement Battle Pass Page UI

- contract/src/lib.cairo
- contract/src/models/character.cairo
- contract/src/tests/test_character.cairo
- Implemented  Character Model and Damage System
> Feat: Character

- contract/src/models/ticket.cairo
- contract/src/tests/test_ticket.cairo
- contract/src/tests/test_world.cairo
-  Created  Tickets Model and Consumption System
> Feat: Tickets 

- contract/src/models/brawler.cairo
- contract/src/systems/brawler.cairo
- contract/src/tests/test_spawn_from_brawler.cairo
Closes #67 
---
This PR adds a new `Brawler` model in Cairo, plus a system to spawn a `Character` from a `Brawler` template.  
It also includes a suite of unit tests to validate proper behavior.
---
- `id` (`felt`) — Unique identifier (`#[key]`)
- `name` (`felt252`) — Brawler's name
- `base_health` (`Uint256`) — Default health value
- `base_attack` (`Uint256`) — Default attack value
- `ability_id` (`felt`) — Link to an existing ability
> Defined in `src/models/brawler.cairo` using `@model` annotation for Dojo compatibility.
---
**File:** `src/systems/brawler.cairo`
- `@external func instantiate_character_from_brawler(...)`
- Reads a `Brawler` by ID
- Validates that the associated `Ability` exists
- Retrieves caller address as `owner`
- Instantiates a new `Character` using …
> feat: add Brawler model

- contract/src/lib.cairo
- contract/src/models/player.cairo
- contract/src/models/quest.cairo
Description
This PR introduces the new Quest model to support daily mission mechanics in Stark Brawl, and also includes important fixes and improvements to the existing Player model. These changes aim to enhance gameplay structure and ensure a more consistent foundation for tracking player progression.
The Quest model defines missions with description, objective, reward, and category fields. The Player model was revised to correct structural issues and to better support future integrations. All changes are covered with unit tests written without relying on the Dojo world or external systems.
Changes Made
Added Quest model with complete mission structure.
Refactored Player model: fixed internal errors, improved data consistency.
Wrote unit tests for both Quest and Player with no use of …
> feat:quest and resolve problems

- contract/src/lib.cairo
- contract/src/models/coins.cairo
- contract/src/models/player.cairo
- Closes #69 
This PR implements the Coins model to manage in-game currency. The implementation creates a dedicated model for tracking player coins, with functions to safely add and spend coins. The system includes overflow protection and balance verification to prevent exploits.
- Created new `Coins` model with player_id (ContractAddress) and amount (u64)
- Implemented `CoinsTrait` with methods for:
- Creating new coin balances
- Adding coins with overflow protection
- Spending coins with balance verification
- Checking if balance is sufficient
- Removed the redundant `coins` field from the Player model to avoid duplication
- Added comprehensive test suite for all coin operations
> [FEAT]: Add coins model

- contract/src/lib.cairo
- contract/src/models/gems.cairo
- Closes #70 
This PR implements the Gems model as specified in issue #XX. Gems are a premium in-game currency that will be used for special purchases and features.
- Created `Gems` model with player_id and amount fields
- Implemented standard traits for manipulation and validation:
- Adding gems with overflow protection
- Spending gems with balance checks
- Helper functions for validation
- Added comprehensive test suite covering all operations
- Used u64 for the gem balance as specified
- Implemented protection against overflow when adding gems
- Added verification to prevent negative balances
- Created foundation for future authorization controls in systems
> [FEAT]: Add gems model

- contract/src/models/item.cairo
This PR fixes an issue where the project isn't compiling on main due to code errors.
> Fix compilation errors

- contract/src/models/leaderboard.cairo
This PR implements the core leaderboard system to track and update player rankings based on match performance. It introduces a new LeaderboardEntry model and a system method to increment scores efficiently. The leaderboard is designed with gas-optimized updates and prepares for future support of top-N player retrievals, potentially off-chain.
- Created LeaderboardEntry model with player_id and score fields  
- Implemented add_score system to update a player’s score  
- Added logic to retrieve and sort leaderboard entries (basic stub or commented placeholder for off-chain handling)  
- Added basic unit tests to verify score accumulation logic
- The sorting logic is not onchain by default to preserve gas efficiency.  
- A future improvement could include off-chain indexing or periodic …
> feat: leaderboard

- contract/src/lib.cairo
- contract/src/models/game.cairo
This PR introduces the `Game` struct and some logic to manage game state.
Closes: #66
> Feat: Match

- contract/src/lib.cairo
- contract/src/models/enemy.cairo
This PR introduces the `Enemy` model to the game logic, enabling tracking and control of enemy entities on-chain.
- `Enemy` model with the following fields:
- `id`: unique identifier
- `enemy_type`: type of enemy (`orc`, `goblin`, `boss`)
- `health`, `speed`, `x`, `y` position
- `is_alive` flag to track active status
- Trait implementation:
- `new`: creates an enemy instance
- `take_damage`: decreases health and updates `is_alive`
- `move_to`: updates position if alive
- Error handling for:
- Overkill (damage to dead enemy)
- InvalidMove (movement after death)
- Full test suite:
- Validates instantiation, survival, death, and panics on invalid actions
All tests pass successfully with `sozo test`.
File: `src/models/enemy.cairo`
---
Closes #101
> feat: add Enemy model with health, movement, and tests

- contract/src/lib.cairo
- contract/src/models/projectile.cairo
This PR introduces the `Projectile` model to represent tower-fired projectiles used to damage enemies in the game.
- **Projectile model fields**:
- `id: u64` — Unique projectile identifier
- `tower_id: u64` — Tower that fired the projectile
- `target_enemy_id: u64` — Enemy being targeted
- `damage: u32` — Damage value on impact
- `speed: u32` — Movement speed
- `x`, `y: u32` — Current position
- `target_x`, `target_y: u32` — Final destination
- **Trait + Implementation**:
- `new`: Creates a new projectile with full metadata
- `has_reached_target`: Returns whether the projectile reached its target
- **Error Handling**:
- `InvalidTarget`: Thrown if target_enemy_id is 0
- **Test Coverage**:
- Creation and attribute checks
- Detection of target arrival
- Panic on invalid enemy target
- …
> feat: projectile model

- client/package-lock.json
- client/package.json
- client/src/App.tsx
- client/src/components/Enemy/EnemyRenderer.tsx
- client/src/components/Map/Game.tsx
- client/src/components/Map/MapRenderer.tsx
- client/src/data/enemySprites.ts
- client/src/logic/class/Enemy.ts
- client/src/logic/controllers/EnemyController.ts
- client/tsconfig.app.json
This PR implements the map and enemy visualization in the main game scene. It contains the initial structure of the `MapRenderer` and the `EnemyRenderer`, with an architecture ready to be extended and dynamically controlled during the game play.
---
- 🗺️ The `MapRenderer` component was created, which renders the map image in a ``<canvas>.
- 🎞️ The `EnemyRenderer` component was created, which draws the animated enemy on the canvas, using the `enemySprites` model with an array of images by animation type.
- 🧩 Everything was integrated within `MainGameScene`, the main component that organizes the map and the enemy on screen.
---
- `components/Map/MapRenderer.tsx`
- `components/Enemy/EnemyRenderer.tsx`
- `components/Map/MainGameScene.tsx`
- `components/logic/class/Enemy.ts`
- …
> feature: create map

- contract/src/lib.cairo
- contract/src/models/map_tile.cairo
- contract/src/tests/test_map_tile.cairo
- contract/src/tests/test_trap.cairo
Closes https://github.com/SunsetLabs-Game/Stark-Brawl/issues/104
> feat: add map_tile

- client/src/components/Enemy/EnemyRenderer.tsx
- client/src/components/Map/Game.tsx
- client/src/components/Map/MapRenderer.tsx
- client/src/components/Map/mapsConfig.ts
- client/src/components/maps-ui/MyMaps.tsx
- client/src/data/enemySprites.ts
- client/src/logic/controllers/EnemyPathController.ts
This PR introduces a comprehensive enemy animation system for the tower defense game, featuring smooth sprite animations, path-following behavior, and manual animation controls while maintaining proper position state management.
fixed #111 
- **Automated pathfinding**: Enemies follow predefined waypoints along the map
- **Smooth movement**: Configurable speed with distance-based waypoint detection
- **State management**: Proper handling of moving, idle, and completed path states
- **Position preservation**: Manual animations no longer reset enemy position to spawn point
- **Multi-frame sprite support**: Loads and displays 10-frame animations for each enemy type
- **Dynamic frame loading**: Efficient asset loading with fallback mechanisms
- **FPS-based timing**: Configurable animation …
> feat: Jungle Ruins Map
